export const data = JSON.parse("{\"key\":\"v-620a6165\",\"path\":\"/posts/2024TSMC_CareerHack.html\",\"title\":\"2024 TSMC CareerHack 心得\",\"lang\":\"en-US\",\"frontmatter\":{\"date\":\"2024-01-28T00:00:00.000Z\",\"category\":[\"Feedbacks\"],\"tag\":[\"TSMC\",\"CareerHack\"],\"description\":\"2024 TSMC CareerHack 心得 前幾天去參加了 2024 台積電的黑客松，大概是人生第一次走進台積辦公室。 這場比賽是一組四人的比賽，前面有一個預賽，需要解出一些簡單的演算法題目。每個人題目會不太相同，但基本上都不會太難，簡單的 Sort、Greedy、Graph、DP。 比賽題目 我們這一組拿到的是 AI 看圖說故事 的題目，基本上就是會有一些工地的照片，希望我們可以去找到 照片中有多少人 有多少人有戴安全帽 有多少人沒戴安全帽 安全帽是甚麼顏色\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/2024TSMC_CareerHack.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Koios Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"2024 TSMC CareerHack 心得\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"2024 TSMC CareerHack 心得 前幾天去參加了 2024 台積電的黑客松，大概是人生第一次走進台積辦公室。 這場比賽是一組四人的比賽，前面有一個預賽，需要解出一些簡單的演算法題目。每個人題目會不太相同，但基本上都不會太難，簡單的 Sort、Greedy、Graph、DP。 比賽題目 我們這一組拿到的是 AI 看圖說故事 的題目，基本上就是會有一些工地的照片，希望我們可以去找到 照片中有多少人 有多少人有戴安全帽 有多少人沒戴安全帽 安全帽是甚麼顏色\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"TSMC\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"CareerHack\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-28T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"2024 TSMC CareerHack 心得\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-01-28T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"比賽題目\",\"slug\":\"比賽題目\",\"link\":\"#比賽題目\",\"children\":[]},{\"level\":2,\"title\":\"比賽過程\",\"slug\":\"比賽過程\",\"link\":\"#比賽過程\",\"children\":[{\"level\":3,\"title\":\"Datasets 處理\",\"slug\":\"datasets-處理\",\"link\":\"#datasets-處理\",\"children\":[]},{\"level\":3,\"title\":\"答案產出\",\"slug\":\"答案產出\",\"link\":\"#答案產出\",\"children\":[]},{\"level\":3,\"title\":\"結果\",\"slug\":\"結果\",\"link\":\"#結果\",\"children\":[]}]},{\"level\":2,\"title\":\"報告\",\"slug\":\"報告\",\"link\":\"#報告\",\"children\":[]},{\"level\":2,\"title\":\"總結\",\"slug\":\"總結\",\"link\":\"#總結\",\"children\":[]}],\"readingTime\":{\"minutes\":4.99,\"words\":1497},\"filePathRelative\":\"posts/2024TSMC_CareerHack.md\",\"localizedDate\":\"January 28, 2024\",\"excerpt\":\"<h1> 2024 TSMC CareerHack 心得</h1>\\n<p>前幾天去參加了 2024 台積電的黑客松，大概是人生第一次走進台積辦公室。</p>\\n<p>這場比賽是一組四人的比賽，前面有一個預賽，需要解出一些簡單的演算法題目。每個人題目會不太相同，但基本上都不會太難，簡單的 Sort、Greedy、Graph、DP。</p>\\n<h2> 比賽題目</h2>\\n<p>我們這一組拿到的是 <strong>AI 看圖說故事</strong> 的題目，基本上就是會有一些工地的照片，希望我們可以去找到</p>\\n<ul>\\n<li>照片中有多少人</li>\\n<li>有多少人有戴安全帽</li>\\n<li>有多少人沒戴安全帽</li>\\n<li>安全帽是甚麼顏色</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
